name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT in both default and test modes
        run: |
          java -jar ./artifacts/app-sut.jar &                             # обычный режим
          java -jar ./artifacts/app-sut.jar --spring.profiles.active=test &  # тестовый режим
          sleep 15  # ждём, пока оба экземпляра приложения поднимутся

      - name: Run tests with Gradle
        run: ./gradlew test --info -Dselenide.headless=true
