name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Run SUT
-        run: java -jar app-deadline.jar --spring.profiles.active=test --server.port=8080 &
+        run: java -jar app-ibank.jar -Pprofile=test &
                - name: Run UI tests
                run: |
                  cd src/test/java
                  mvn test