name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT in test mode
        run: |
          java -jar ./artifacts/app-sut.jar --server.port=8080 --spring.profiles.active=test &
          sleep 5

      - name: Wait for SUT to start
        run: |
          until curl -s http://localhost:8080; do
            sleep 1
          done

      - name: Run tests with Gradle
        run: ./gradlew test --info -Dselenide.headless=true

      - name: Stop SUT
        if: always()
        run: pkill -f 'java -jar ./artifacts/app-sut.jar'