name: Autotests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Start app-ibank in test mode
        run: java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -Dspring.datasource.username=app -Dspring.datasource.password=pass -jar app-ibank.jar -P:test &

      - name: Wait for app to start
        run: sleep 20

      - name: Run tests in headless mode
        run: ./gradlew clean test -Dselenide.headless=true

      - name: Archive test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: build/reports/tests/test
