name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT in test mode
        run: |
          java -jar ./artifacts/app-ibank.jar -P:profile-test &

      - name: Run tests
        run: ./gradlew test --info -Dselenide.headless=true